name: SEC
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  scan_secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Trufflehog Check
      uses: UnicornGlobal/trufflehog-actions-scan@v1.0.0
      with:
        branch: develop
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.